export type ValueCategory = {
  id: string;
  emoji: string;
  title: string;
  items: { id: number; text: string }[];
};

export const VALUE_CATEGORIES: ValueCategory[] = [
  {
    id: "relaciones",
    emoji: "❤️",
    title: "Atender a las relaciones",
    items: [
      { id: 1, text: "Reparar viejas relaciones." },
      { id: 2, text: "Buscar nuevas relaciones." },
      { id: 3, text: "Trabajar y cultivar las relaciones actuales." },
      { id: 4, text: "Terminar con aquellas relaciones que son destructivas." },
    ],
  },
  {
    id: "grupo",
    emoji: "👥",
    title: "Pertenecer a un grupo",
    items: [
      { id: 5, text: "Tener relaciones cercanas y satisfacer con otros." },
      { id: 6, text: "Tener sentido de pertenencia." },
      { id: 7, text: "Recibir y dar afecto y cariño." },
      { id: 8, text: "Estar involucrado/a e intimar con otros, tener y mantener amigos cercanos." },
      { id: 9, text: "Tener una familia con quien pasar momentos placenteros." },
      { id: 10, text: "Estar con personas con las cuales hacer cosas, organizar salidas." },
    ],
  },
  {
    id: "poder",
    emoji: "👑",
    title: "Ser poderoso/a e influenciar a otros",
    items: [
      { id: 11, text: "Tener la autoridad para aprobar o desaprobar lo que la gente hace, controlar la manera en la cual se utilizan los recursos." },
      { id: 12, text: "Ser un líder." },
      { id: 13, text: "Hacer mucho dinero." },
      { id: 14, text: "Ser respetado/a por otros." },
      { id: 15, text: "Ser visto/a por otros como exitoso/a; obtener reconocimiento y estatus." },
      { id: 16, text: "Competir de manera exitosa con otros." },
      { id: 17, text: "Ser popular y aceptado/a." },
    ],
  },
  {
    id: "metas",
    emoji: "🎯",
    title: "Lograr metas en la vida",
    items: [
      { id: 18, text: "Alcanzar metas significativas en la vida." },
      { id: 19, text: "Estar involucrado/a en cosas que creo, personalmente, que son importantes." },
      { id: 20, text: "Ser productivo/a." },
      { id: 21, text: "Trabajar en pos de objetivos, metas, trabajar duro." },
    ],
  },
  {
    id: "placer",
    emoji: "🌸",
    title: "Vivir una vida de placer y satisfacción",
    items: [
      { id: 22, text: "Pasar buenos momentos." },
      { id: 23, text: "Probar situaciones divertidas y objetos o cosas que den placer." },
      { id: 24, text: "Tener tiempo libre." },
      { id: 25, text: "Disfrutar el trabajo que hago." },
    ],
  },
  {
    id: "estimulos",
    emoji: "✨",
    title: "Tener una vida llena de eventos, relaciones y estímulos",
    items: [
      { id: 26, text: "Probar cosas nuevas y diferentes en la vida." },
      { id: 27, text: "Ser abierto/a, curioso/a y buscar nuevas aventuras." },
      { id: 28, text: "Tener una vida excitante." },
    ],
  },
  {
    id: "respeto",
    emoji: "🤝",
    title: "Comportarme de manera respetuosa",
    items: [
      { id: 29, text: "Ser humilde y modesto/a, sin llamar la atención." },
      { id: 30, text: "Seguir tradiciones y costumbres de manera adecuada." },
      { id: 31, text: "Acatarme a las reglas." },
      { id: 32, text: "Tratar bien a los otros." },
    ],
  },
  {
    id: "independiente",
    emoji: "🦅",
    title: "Ser independiente",
    items: [
      { id: 33, text: "Seguir mi propio camino en la vida." },
      { id: 34, text: "Ser innovador/a, pensar nuevas ideas y ser creativo/a." },
      { id: 35, text: "Tomar mis propias decisiones y ser libre." },
      { id: 36, text: "Ser independiente y cuidar de mí mismo/a y de aquellos de los cuales soy responsable." },
      { id: 37, text: "Tener libertad para pensar y actuar según mis prioridades." },
    ],
  },
  {
    id: "espiritual",
    emoji: "🕊️",
    title: "Ser una persona espiritual",
    items: [
      { id: 38, text: "Otorgarle un lugar en la vida diaria a la espiritualidad, vivir acorde a ella." },
      { id: 39, text: "Practicar una religión o fe." },
      { id: 40, text: "Crecer en la comprensión de mí mismo/a." },
      { id: 41, text: "Discernir y actuar según la voluntad de Dios (o un poder superior) y encontrar el significado de la vida." },
    ],
  },
  {
    id: "seguridad",
    emoji: "🛡️",
    title: "Estar seguro/a",
    items: [
      { id: 42, text: "Vivir en ambientes seguros." },
      { id: 43, text: "Estar sano/a físicamente y en buen estado físico." },
      { id: 44, text: "Tener un ingreso promedio que me permita a mí y a mi familia cubrir las necesidades básicas." },
    ],
  },
  {
    id: "bondad",
    emoji: "🌍",
    title: "Reconocer la bondad universal",
    items: [
      { id: 45, text: "Ser justo/a, tratar a las personas de manera ecuánime y darles las mismas oportunidades." },
      { id: 46, text: "Entender a las personas que son diferentes, tener una mente abierta." },
      { id: 47, text: "Darle importancia al ambiente y a la naturaleza." },
    ],
  },
  {
    id: "comunidad",
    emoji: "🤲",
    title: "Contribuir a la comunidad",
    items: [
      { id: 48, text: "Ayudar a quienes lo necesitan; mejorar el bienestar de los otros, de la sociedad." },
      { id: 49, text: "Ser leal a los amigos, y a las personas cercanas, estar involucrado/a con un grupo que comparta mis valores, creencias y principios éticos." },
      { id: 50, text: "Estar comprometido/a con una causa o con un grupo que tenga un propósito que vaya más allá del propio." },
      { id: 51, text: "Hacer sacrificios por los demás." },
    ],
  },
  {
    id: "desarrollo",
    emoji: "🌱",
    title: "Trabajar en el desarrollo personal",
    items: [
      { id: 52, text: "Desarrollar una filosofía de vida." },
      { id: 53, text: "Aprender y atravesar por retos que me ayuden a crecer y madurar como ser humano." },
    ],
  },
  {
    id: "integridad",
    emoji: "💎",
    title: "Tener integridad",
    items: [
      { id: 54, text: "Ser honesto/a y apegarme a mis creencias personales." },
      { id: 55, text: "Ser una persona responsable, cumplir mi palabra." },
      { id: 56, text: "Tener coraje al encarar y vivir la vida." },
      { id: 57, text: "Ser una persona que paga sus deudas y repara el daño que ha causado." },
      { id: 58, text: "Aceptarme a mí mismo/a, a los otros y a la vida como es, sin resentimientos." },
    ],
  },
];

export type Activity = { id: number; name: string; category: string };

export const ACTIVITIES: Activity[] = [
  { id: 1, name: "Lavar, limpiar o arreglar mi vehículo, bicicleta o moto", category: "Orden" },
  { id: 2, name: "Planear una carrera, capacitación o proyecto personal", category: "Logro" },
  { id: 3, name: "Pagar las deudas y organizar mis cuentas", category: "Orden" },
  { id: 4, name: "Coleccionar cosas (monedas, estampillas, caracoles, discos)", category: "Ocio" },
  { id: 5, name: "Ir de vacaciones o planificar una escapada", category: "Ocio" },
  { id: 6, name: "Pensar cómo será mi vida cuando termine mi formación", category: "Logro" },
  { id: 7, name: "Reciclar cosas viejas o restaurar un objeto", category: "Creativo" },
  { id: 8, name: "Ir a una cita romántica o salida especial", category: "Social" },
  { id: 9, name: "Relajarme recostado/a sin hacer absolutamente nada", category: "Autocuidado" },
  { id: 10, name: "Ir al cine a ver una película esperada", category: "Ocio" },
  { id: 11, name: "Trotar, caminar rápido o hacer running", category: "Deportes" },
  { id: 12, name: 'Pensar: "He trabajado muy duro todo el día"', category: "Logro" },
  { id: 13, name: "Escuchar música que me guste de forma atenta", category: "Ocio" },
  { id: 14, name: "Pensar en fiestas pasadas o recuerdos hermosos", category: "Ocio" },
  { id: 15, name: "Comprar electrodomésticos o cosas para embellecer mi hogar", category: "Orden" },
  { id: 16, name: "Recostarme un rato al sol en el jardín o parque", category: "Autocuidado" },
  { id: 17, name: "Planear un cambio de carrera o de profesión", category: "Logro" },
  { id: 18, name: "Reír a carcajadas con una comedia o chiste", category: "Ocio" },
  { id: 19, name: "Planificar o investigar sobre viajes futuros", category: "Ocio" },
  { id: 20, name: "Escuchar de manera activa y conversar con alguien", category: "Social" },
  { id: 21, name: "Leer novelas, revistas o el diario físico", category: "Ocio" },
  { id: 22, name: "Tomar clases de baile o bailar libremente en casa", category: "Deportes" },
  { id: 23, name: "Pasar una tarde divertida con mis mejores amigos", category: "Social" },
  { id: 24, name: "Planificar detalladamente las actividades del día o de la semana", category: "Orden" },
  { id: 25, name: "Conocer gente nueva o interactuar en un grupo nuevo", category: "Social" },
  { id: 26, name: "Recordar paisajes hermosos u obras de arte que visité", category: "Autocuidado" },
  { id: 27, name: "Ahorrar dinero y guardarlo en una alcancía o cuenta", category: "Orden" },
  { id: 28, name: "Volver a casa sintiendo el alivio del día terminado", category: "Autocuidado" },
  { id: 29, name: "Comer un plato favorito o cocinar una receta gourmet nueva", category: "Autocuidado" },
  { id: 30, name: "Practicar artes marciales, karate, judo o yoga", category: "Deportes" },
  { id: 31, name: "Pensar de manera positiva sobre el momento de mi jubilación", category: "Ocio" },
  { id: 32, name: "Reparar y pintar cosas rotas de la casa", category: "Orden" },
  { id: 33, name: "Trabajar en carpintería, manualidades o reparar maquinaria", category: "Creativo" },
  { id: 34, name: "Recordar palabras de afecto o elogios de seres queridos", category: "Social" },
  { id: 35, name: "Vestirme con ropa que me haga sentir lindo/a e impactante", category: "Autocuidado" },
  { id: 36, name: "Tener una tarde tranquila de lectura silenciosa", category: "Ocio" },
  { id: 37, name: "Cuidar de mis plantas, regar el jardín o podar", category: "Naturaleza" },
  { id: 38, name: "Comprar o vender cosas de forma inteligente", category: "Orden" },
  { id: 39, name: "Ir a nadar a una pileta, club o río", category: "Deportes" },
  { id: 40, name: "Dibujar, hacer bosquejos o pintar con pinceles", category: "Creativo" },
  { id: 41, name: "Hacer ejercicios de levantamiento de pesas o calistenia", category: "Deportes" },
  { id: 42, name: "Hacer limpieza profunda de placares o tirar lo que no sirve", category: "Orden" },
  { id: 43, name: "Ir a una fiesta, peña o club social", category: "Social" },
  { id: 44, name: "Comprar cosas agradables de mi lista de deseos", category: "Ocio" },
  { id: 45, name: "Jugar al golf, minigolf o juegos de precisión", category: "Deportes" },
  { id: 46, name: "Jugar al fútbol, básquet o tenis con un equipo", category: "Deportes" },
  { id: 47, name: "Remontar un barrilete o cometa en un día de viento", category: "Naturaleza" },
  { id: 48, name: "Tener una charla telefónica prolongada con alguien querido", category: "Social" },
  { id: 49, name: "Organizar y disfrutar de una gran comida familiar", category: "Social" },
  { id: 50, name: "Dar un paseo en bicicleta de forma recreativa", category: "Deportes" },
  { id: 51, name: "Hacer atletismo, caminar por senderos o senderismo", category: "Naturaleza" },
  { id: 52, name: "Ir de campamento o planear dormir bajo las estrellas", category: "Naturaleza" },
  { id: 53, name: "Cantar solo/a o con un grupo en voz alta", category: "Ocio" },
  { id: 54, name: "Diseñar un arreglo floral o armar un cantero de jardín", category: "Naturaleza" },
  { id: 55, name: "Meditar, rezar o tener una práctica de conexión espiritual", category: "Autocuidado" },
  { id: 56, name: "Organizar y limpiar mis herramientas o escritorio de trabajo", category: "Orden" },
  { id: 57, name: "Caminar descalzo/a por el pasto o por la arena del río", category: "Naturaleza" },
  { id: 58, name: 'Pensar con firmeza: "Soy una persona que vale la pena"', category: "Autocuidado" },
  { id: 59, name: "Tener un día completo libre de compromisos y obligaciones", category: "Autocuidado" },
  { id: 60, name: "Organizar una noche de juegos de mesa y cartas", category: "Social" },
  { id: 61, name: "Ir a patinar en rollers o sobre hielo", category: "Deportes" },
  { id: 62, name: "Navegar en kayak, bote o velero", category: "Naturaleza" },
  { id: 63, name: "Viajar a un lugar cercano que no conozco", category: "Ocio" },
  { id: 64, name: "Pintar una pared o cambiar la decoración de mi cuarto", category: "Creativo" },
  { id: 65, name: "Salir a caminar de manera espontánea sin rumbo fijo", category: "Ocio" },
  { id: 66, name: "Coser, tejer, hacer crochet o bordar un diseño", category: "Creativo" },
  { id: 67, name: "Dormir una siesta reconfortante por la tarde sin despertador", category: "Autocuidado" },
  { id: 68, name: "Conducir o viajar en auto por un camino con hermosas vistas", category: "Naturaleza" },
  { id: 69, name: "Organizar una gran fiesta sorpresa para un amigo/a", category: "Social" },
  { id: 70, name: "Visitar un vivero, jardín botánico o parque de rosas", category: "Naturaleza" },
  { id: 71, name: "Pensar positivamente en los proyectos futuros de mi familia", category: "Social" },
  { id: 72, name: "Visitar una biblioteca pública o comprar libros", category: "Creativo" },
];

export const DAYS = ["lun", "mar", "mié", "jue", "vie", "sáb", "dom"] as const;
export const DAY_LABELS = ["LUN", "MAR", "MIÉ", "JUE", "VIE", "SÁB", "DOM"];
export const HOURS = ["08:00", "10:00", "12:00", "14:00", "16:00", "18:00", "20:00", "22:00"] as const;
